from pathlib import Path
import json,re,subprocess,sys
import numpy as np
import pandas as pd
ROOT=Path(__file__).resolve().parents[1]
checks=[]
def chk(name,ok,detail=''): checks.append({'name':name,'status':'PASS' if ok else 'FAIL','detail':detail})
required=['README.md','requirements.txt','pyproject.toml','.github/workflows/ci.yml','src/simulation.py','scripts/generate_synthetic_data.py','scripts/statistical_qa.py','scripts/run_doe.py','scripts/run_msa.py','docs/operational-definitions.md','docs/copq-methodology.md','docs/capability-methodology.md','docs/data-generating-process.md','docs/limitations.md','dmaic/01_define/project-charter.md','dmaic/05_control/control-plan.md']
chk('repository_structure',all((ROOT/p).exists() for p in required),str([p for p in required if not (ROOT/p).exists()]))
df=pd.read_csv(ROOT/'data'/'interim'/'applications_true.csv',low_memory=False); clean=pd.read_csv(ROOT/'data'/'clean'/'applications_clean.csv',low_memory=False); cap=pd.read_csv(ROOT/'data'/'interim'/'capacity_schedule.csv'); cal=pd.read_csv(ROOT/'data'/'interim'/'business_calendar.csv'); analysts=pd.read_csv(ROOT/'data'/'interim'/'analyst_dimension.csv'); events=pd.read_csv(ROOT/'data'/'interim'/'special_cause_manifest.csv'); msa=pd.read_csv(ROOT/'data'/'msa'/'msa_study.csv'); doe=pd.read_csv(ROOT/'data'/'doe'/'doe_experiment.csv')
chk('canonical_generation',len(df)>0); chk('exact_row_count',len(df)==100000,f'n={len(df)}'); chk('deterministic_manifest',json.loads((ROOT/'results'/'generation_manifest.json').read_text())['seed']==42); chk('unique_ids',df.Application_ID.is_unique)
chk('calendar_integrity',cal.Date.nunique()==len(cal)); cmap=dict(zip(cal.Date,cal.Branch_Open)); chk('channel_calendar_consistency',all(bool(cmap[d]) for d in df.loc[df.Channel.eq('Branch'),'Application_Date'].astype(str)))
chk('timestamp_ordering',pd.to_datetime(df.loc[df.Completed_Flag.eq(1),'Activation_Timestamp']).ge(pd.to_datetime(df.loc[df.Completed_Flag.eq(1),'Approval_Timestamp'])).all()); chk('abandonment_censoring',df.loc[df.Abandonment_Flag.eq(1),['Approval_Timestamp','Activation_Timestamp']].isna().all().all()); chk('completed_record_integrity',df.loc[df.Completed_Flag.eq(1),['Approval_Timestamp','Activation_Timestamp']].notna().all().all())
chk('staffing_grain',cap[['Date','Branch_ID','Shift']].drop_duplicates().shape[0]==len(cap)); chk('capacity_reconciliation',((cap.Opening_Backlog+cap.New_Arrivals-cap.Processed_Count-cap.Closing_Backlog).abs()<.03).all())
rec_ok=True
for _,g in cap.sort_values(['Branch_ID','Shift','Date']).groupby(['Branch_ID','Shift']): rec_ok &= np.allclose(g.Opening_Backlog.iloc[1:],g.Closing_Backlog.iloc[:-1],atol=.02)
chk('backlog_recursion',bool(rec_ok)); chk('outage_overlap_fields',{'System_Downtime_Minutes'}.issubset(cap.columns)); chk('analyst_integrity',analysts.Analyst_ID.is_unique and df.Analyst_ID.isin(analysts.Analyst_ID).all())
expected=np.where(df.Complexity_Score<=29,'Low',np.where(df.Complexity_Score<=49,'Medium','High')); chk('complexity_stability',np.all(expected==df.Application_Complexity)); exp_r=np.where(df.Risk_Score<35,'Low',np.where(df.Risk_Score<65,'Medium','High')); chk('risk_methodology',np.all(exp_r==df.Risk_Tier))
defcols=[c for c in df if c.endswith('_Defect')]; chk('defect_opportunities',len(defcols)==6 and np.array_equal(df.Defect_Count.values,df[defcols].sum(axis=1).values)); chk('dpmo_inputs',len(defcols)>0)
chk('cost_of_quality',np.allclose(df.Total_Cost_of_Quality,df.Total_Prevention_Cost+df.Total_Appraisal_Cost+df.Total_COPQ)); chk('copq_reconciliation',np.allclose(df.Total_COPQ,df.Total_Internal_Failure_Cost+df.Total_External_Failure_Cost)); chk('required_control_excluded_from_copq',np.allclose(df.Total_Appraisal_Cost,df.Required_Manual_Review_Cost))
gt=pd.read_csv(ROOT/'data'/'interim'/'injected_issues_ground_truth.csv'); det=pd.read_csv(ROOT/'data'/'data_quality_issues.csv'); a=set(map(tuple,gt[['Application_ID','Issue_Type']].values)); b=set(map(tuple,det[['Application_ID','Issue_Type']].values)); chk('quality_issue_seeding',len(a)==3200); chk('detection_precision',len(a&b)/len(b)==1); chk('detection_recall',len(a&b)/len(a)==1); raw=pd.read_csv(ROOT/'data'/'raw'/'applications_raw.csv',low_memory=False); q=pd.read_csv(ROOT/'data'/'quarantine'/'applications_quarantine.csv',low_memory=False); chk('clean_reconciliation',len(raw)==len(clean)+len(q))
chk('msa_design',len(msa)==960 and msa.Reviewer_ID.nunique()==4 and msa.Trial.nunique()==2 and msa.Study_Phase.nunique()==2); chk('doe_balance',len(doe.groupby(['Staffing_Capacity','Document_Prevalidation','Routing_Strategy']))==8 and doe.groupby(['Staffing_Capacity','Document_Prevalidation','Routing_Strategy']).size().nunique()==1); chk('doe_execution',(ROOT/'results'/'doe_results.json').exists()); chk('spc_outputs',(ROOT/'results'/'spc_results.json').exists()); chk('special_cause_manifest',len(events)>0 and events.Event_ID.is_unique); chk('regression_diagnostics',json.loads((ROOT/'results'/'regression_results.json').read_text())['max_vif']<10); chk('capability_methodology',(ROOT/'results'/'capability_by_tier.csv').exists()); seeds=pd.read_csv(ROOT/'results'/'seed_robustness.csv'); chk('multi_seed_robustness',len(seeds)==5 and seeds.Rows.eq(100000).all()); stat=json.loads((ROOT/'results'/'statistical_qa.json').read_text()); chk('statistical_qa',stat['overall']=='PASS')
# docs and links
md=list(ROOT.rglob('*.md')); chk('documentation',len(md)>=15,f'{len(md)} markdown files'); text='\n'.join(p.read_text(errors='ignore') for p in md); chk('synthetic_disclosure','synthetic' in text.lower()); bad_placeholders=re.findall(r'\b(TODO|TBD|LOREM IPSUM|COMING SOON)\b',text,re.I); chk('no_placeholders',not bad_placeholders,str(bad_placeholders[:5])); chk('privacy_no_real_customer_names',not re.search(r'\b(customer name|account number)\s*:',text,re.I)); chk('no_credentials',not re.search(r'(api[_-]?key|password|secret)\s*[:=]\s*["\'][^"\']+',text,re.I)); chk('python_syntax',subprocess.run([sys.executable,'-m','compileall','-q',str(ROOT/'src'),str(ROOT/'scripts')]).returncode==0); chk('sql_coverage',len(list((ROOT/'sql').glob('*.sql')))>=5); chk('ci_wiring',(ROOT/'.github/workflows/ci.yml').exists()); manifest=json.loads((ROOT/'results'/'generation_manifest.json').read_text()); chk('output_hashes',len(manifest.get('output_hashes',{}))>=6); chk('repository_hygiene',(ROOT/'.gitignore').exists()); chk('readme_metrics',(ROOT/'README.md').exists() and 'First Pass Yield' in (ROOT/'README.md').read_text()); chk('operational_definitions',(ROOT/'docs/operational-definitions.md').exists()); chk('causal_map',(ROOT/'docs/data-generating-process.md').exists()); chk('control_phase',(ROOT/'results'/'control_results.json').exists()); chk('pilot_phase',(ROOT/'results'/'pilot_results.json').exists()); chk('fmea',(ROOT/'results'/'fmea.csv').exists()); chk('hypothesis_tests',(ROOT/'results'/'hypothesis_tests.json').exists())
overall=all(c['status']=='PASS' for c in checks); report={'passed':sum(c['status']=='PASS' for c in checks),'total':len(checks),'overall':'PASS' if overall else 'FAIL','checks':checks}; (ROOT/'results'/'qa_report.json').write_text(json.dumps(report,indent=2)); print(json.dumps({'passed':report['passed'],'total':report['total'],'overall':report['overall'],'failures':[c for c in checks if c['status']=='FAIL']},indent=2)); sys.exit(0 if overall else 1)
